spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tourism
    username: root
    password: 0000password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect